"""Repository protocol defining the storage interface for all entity types."""

from typing import Protocol


class Repository(Protocol):
    """Abstract storage interface.

    Any class that implements these methods satisfies the protocol
    (structural subtyping — no inheritance required).
    """

    # --- Rooms ---
    def save_room(self, room_id: str, name: str, color: str) -> None: ...
    def delete_room(self, room_id: str) -> None: ...
    def load_all_rooms(self) -> dict[str, dict]: ...

    # --- Trackers ---
    def save_tracker(self, entity_id: str, mobile: bool, whitelist: bool, blacklist: bool) -> None: ...
    def delete_tracker(self, entity_id: str) -> None: ...
    def load_all_trackers(self) -> dict[str, dict]: ...

    # --- Sensors ---
    def save_sensor(self, entity_id: str, mobile: bool) -> None: ...
    def delete_sensor(self, entity_id: str) -> None: ...
    def load_all_sensors(self) -> dict[str, dict]: ...

    # --- Beacon Monitors ---
    def save_beacon_monitor(self, entity_id: str) -> None: ...
    def delete_beacon_monitor(self, entity_id: str) -> None: ...
    def load_all_beacon_monitors(self) -> dict[str, dict]: ...

    # --- Beacon Names ---
    def save_beacon_name(self, beacon_id: str, friendly_name: str) -> None: ...
    def delete_beacon_name(self, beacon_id: str) -> None: ...
    def load_all_beacon_names(self) -> dict[str, str]: ...

    # --- Devices ---
    def save_device(self, device_id: str, name: str, entity_id: str | None, beacon_id: str | None) -> None: ...
    def delete_device(self, device_id: str) -> None: ...
    def load_all_devices(self) -> dict[str, dict]: ...

    # --- Model Metadata ---
    def save_model_metadata(
        self,
        device_id: str,
        data_path: str,
        accuracy: float,
        model_type: str,
        classification_report: dict,
        trained_columns: list[str],
    ) -> None: ...
    def delete_model_metadata(self, device_id: str) -> None: ...
    def load_model_metadata(self, device_id: str) -> dict | None: ...

    # --- Lifecycle ---
    def close(self) -> None: ...
